### ISSUE TITLE
Add topics/keywords to the repo

### ISSUE THREAD

**Issue by XDMeister1337** [Onlyartist9/European-Tech-Internships-2023#3]
I saw this with another repo where they had topics attached such as "Internships" or "University", and I believe that it would be helpful to add that in for this repo as well.

**Comment by Onlyartist9** [comment]
Something like tags right?

**Comment by Onlyartist9** [comment]
> I saw this with another repo where they had topics attached such as "Internships" or "University", and I believe that it would be helpful to add that in for this repo as well.

So something like tags right? Link to the repo? Want to see how it's implemented.

**Comment by XDMeister1337** [comment]
https://github.com/pittcsc/Summer2023-Internships

**Comment by Onlyartist9** [comment]
Oh, I get what you mean. On it!

**Comment by Onlyartist9** [comment]
How does it look now? @XDMeister1337

**Comment by XDMeister1337** [comment]
It looks good to me now. Thanks!
